repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    - id: black
      name: black
      description: "Black: The uncompromising Python code formatter"
      entry: black
      language: python
      minimum_pre_commit_version: 2.9.2
      require_serial: true
      types_or: [python, pyi]
    - id: black-jupyter
      name: black-jupyter
      description:
        "Black: The uncompromising Python code formatter (with Jupyter Notebook support)"
      entry: black
      language: python
      minimum_pre_commit_version: 2.9.2
      require_serial: true
      types_or: [python, pyi, jupyter]
      additional_dependencies: [".[jupyter]"]

  - repo: local
    hooks:
    -   id: clean-pycache
        name: Clean Python Cache Files
        entry: bash -c 'find . -type d -name "__pycache__" -exec rm -r {} + && find . -type f -name "*.pyc" -delete'
        language: system
        always_run: true
        pass_filenames: false
