ROUTE = 'https://data.etabus.gov.hk/v1/transport/kmb/route/'
STOP = 'https://data.etabus.gov.hk/v1/transport/kmb/stop'
ROUTE_STOP = 'https://data.etabus.gov.hk/v1/transport/kmb/route-stop'
STOP_DETAIL = 'https://data.etabus.gov.hk/v1/transport/kmb/stop/{stop_id}'
TIMETABLE = 'https://search.kmb.hk/KMBWebSite/Function/FunctionRequest.ashx?action=getschedule&route={route}&bound={bound}'
